# Generated by Django 4.0.2 on 2022-06-28 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_pledge_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='type',
            field=models.CharField(choices=[('$', 'Money'), ('T', 'Time'), ('A', 'Advice'), ('R', 'Resources'), ('O', 'Other')], max_length=20),
        ),
    ]
