# Generated by Django 4.0.2 on 2022-07-02 01:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_pledge_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='seeking',
            field=models.CharField(choices=[('$', 'Money'), ('T', 'Time'), ('A', 'Advice'), ('R', 'Resources'), ('O', 'Other')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
