# Generated by Django 4.0.2 on 2022-07-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_seeking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pledge',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
