# Generated by Django 4.0.2 on 2022-07-02 01:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_alter_pledge_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='categories',
            field=models.CharField(choices=[('1', 'Technology'), ('2', 'Environment'), ('3', 'Sustainability'), ('4', 'Education'), ('5', 'Diversity & Inclusion'), ('6', 'Community Building & Events'), ('7', 'Human Rights'), ('9', 'International'), ('10', 'Other')], default=django.utils.timezone.now, max_length=20),
            preserve_default=False,
        ),
    ]
