# Generated by Django 4.0.2 on 2022-07-02 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_project_categories'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categories', models.CharField(choices=[('1', 'Technology'), ('2', 'Environment or Sustainability'), ('3', 'Education'), ('4', 'Diversity & Inclusion'), ('5', 'Community Building & Events'), ('6', 'Human Rights'), ('7', 'International'), ('8', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='PledgeTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pledge_types', models.CharField(choices=[('$', 'Money'), ('T', 'Time'), ('A', 'Advice'), ('R', 'Resources'), ('O', 'Other')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Seeking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seeking_for', models.CharField(choices=[('S', 'Software Development'), ('M', 'Marketing & Branding'), ('B', 'Tax/Accounting/Legal Expertise'), ('I', 'Industry-specific Expertise'), ('C', 'Events & Community Engagement'), ('E', 'Looking to gain work experience'), ('A', 'Happy to assist with whatever is needed')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skills', models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='pledge',
            name='anonymous',
        ),
        migrations.RemoveField(
            model_name='project',
            name='categories',
        ),
        migrations.AlterField(
            model_name='pledge',
            name='comment',
            field=models.CharField(max_length=300),
        ),
        migrations.RemoveField(
            model_name='project',
            name='seeking',
        ),
        migrations.AddField(
            model_name='project',
            name='select_categories',
            field=models.ManyToManyField(to='projects.Categories'),
        ),
        migrations.AddField(
            model_name='project',
            name='seeking',
            field=models.ManyToManyField(to='projects.PledgeTypes'),
        ),
    ]
